# Development Dockerfile for ROS2 with Nvidia GPU support
# Maintainer: Dayuan
services:
  ros2_cuda:
    container_name: ros2_humble_cuda
    image: ros2_cuda_docker
    build: ./
    volumes:
      - ./packages:/root/ws/src/
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    network_mode: "host"  # Must with this line to enable display
    ipc: host

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Request all available GPUs. Can also be an integer (e.g., 1) or a specific ID
              capabilities: [gpu, graphics, utility, display] # Required field to specify GPU access

    devices:
      - /dev/dri:/dev/dri
    
    privileged: true
    stdin_open: true
    tty: true